name: ArrowPickup
main: com.samistine.arrowpickup.ArrowPickup
version: ${project.version}-b${BUILD_NUMBER}

git_repo: https://github.com/Samistine/ArrowPickup
git_hash: ${git_hash}
jenkins_build: ${BUILD_NUMBER}

description: Pickup all arrows including those from skeletons
author: Sycholic && Samistine